---

- name: install builder
  hosts: localhost
  connection: local
 # become: yes
  gather_facts: False
  vars:
  vars_files:
    - vars.yml
  tasks:

  - name: Create a keypair
    ec2_key:
      name: '{{ keyname }}'
      region: '{{ region }}'
      #state: absent
    register: ec2_key_result

  - name: Save kaypair
    copy:
      content: "{{ ec2_key_result.key.private_key }}"
      dest: /root/.ssh/{{ keyname }}.pem
      mode: 0600
    when: ec2_key_result.changed

  - name: Create new security group
    ec2_group:
      name: '{{ security-group }}'
      description: '{{ sg-decsription }}'
      region: '{{ region }}'
      rules:
        - proto: tcp
          ports:
            - 0-65535
          cidr_ip: 0.0.0.0/0

  - name: Create Build nstance
    ec2_instance:
      key_name: '{{ keyname }}'
      instance_type: '{{ instance-type }}'
      image_id: ami-0bd9c26722573e69b
      tags:
        name: Builder
      security_group: '{{ security-group }}'
      wait: yes
      # wait_timeout: 180
     # count: 1
      region: '{{ region }}'
    register: ec21

  - name: Add Build instance to host group
    add_host:
      hostname: "{{ item.public_ip_address }}"
      groups: Builders
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: /root/.ssh/'{{ keyname }}'
    with_items: "{{ ec21.instances }}"


  - name: Wait for SSH to come up
    local_action: wait_for
                host={{ item.public_ip_address }}
                port=22
                state=started
    with_items: "{{ ec21.instances }}"

 # - name: Wait for SSH to come up
  #  delegate_to: "{{ item.public_dns_name }}"
  # wait_for_connection:
   #   delay: 60
    #  timeout: 320
   # with_items: "{{ ec21.instances }}"




- name: Configure instances
  hosts: Builders
  become: True
  gather_facts: True

  tasks:

  - name: Ensure JDK is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure MAVEN is present
    apt:
      name: maven
      state: present

  - name: Ensure GIT is present
    apt:
      name: git
      state: present

  - name: Get SRC APP from git
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /var/boxfuse_src

  - name: BUILD APP
    shell: mvn package
    args:
      chdir: /var/boxfuse_src


  - name: Simple PUT operation
    aws_s3:
      bucket: mybucket
      object: /my/desired/key.txt
      src: /usr/local/myfile.txt
      mode: put

  - name: FETCH APP
    fetch:
      src: /var/boxfuse_src/target/hello-1.0.war
      dest: /home/ubuntu/
      flat: yes